<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting><AssemblyName>MonthlyProfit</AssemblyName><ApplicationManifest>app.manifest</ApplicationManifest><DebugType>none</DebugType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Core/Profit.Core.csproj" /></ItemGroup>
</Project>
